import Navbar from './components/navbar'
import './globals.css'
import { Mulish } from 'next/font/google'

const mulish = Mulish({ subsets: ['latin'] })

export const metadata = {
  title: 'Toko Online',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <header className='border-b-[1px]'>
          <Navbar/>
        </header>
        {children}
      </body>
    </html>
  )
}
